### ISSUE TITLE
Reduce load time

### ISSUE THREAD

**Issue by thesohelshaikh** [thesohelshaikh/iste_itnu_2018#12]

**Comment by sdabhi23** [comment]
Maybe you can use lower resolution images, or a different set of images for each resolution (e.g.: hdpi, mdpi, etc). Or you can lazy load the images once the main content has been rendered.

**Comment by thesohelshaikh** [comment]
https://gist.github.com/thesohelshaikh/115a4484b72a38856cac91bd13695091

**Comment by sdabhi23** [comment]
Well, I can see that it's a report for the homepage. How about an audit for team.html? 🤔 

That's the page with the highest number of images. Also I just noticed that it doesn't render  the images of the members when accessed from a smartphone, and the circular avatars become elliptical on tablets.

**Comment by thesohelshaikh** [comment]
Images are hidden on mobile devices.  Noted suggestion #19. Thanks 👍
