### ISSUE TITLE
Page width issue

### ISSUE THREAD

**Issue by sdabhi23** [thesohelshaikh/iste_itnu_2018#18]
Every page has some gap on the right margin, which looks aesthetically bad, and introduces horizontal scrolling as well, which may cause issues when adding gestures to carousels.

**Comment by thesohelshaikh** [comment]
Review and confirm @sdabhi23.

**Comment by sdabhi23** [comment]
Looks like it's fixed @thesohelshaikh

**Comment by thesohelshaikh** [comment]
Dirty fix. Closing for now. Messes with row margins throughout the site. 😒

**Comment by sdabhi23** [comment]
Obviously 🤷‍♂️ . A better approach would be to add a new class to the offending elements and remove margins through that class.

**Comment by thesohelshaikh** [comment]
Fixed in latest commit. 😌
